[server]
port = 8501
address = "0.0.0.0"
headless = true

[client]
showSidebarNavigation = false

[theme]
primaryColor = "#84ABFF"
backgroundColor = "#F8FAFC"
secondaryBackgroundColor = "#F1F5F9"
textColor = "#0F172A"
font = "sans serif"

[browser]
serverAddress = "0.0.0.0"